# Generated by Django 2.2.7 on 2019-11-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eng", "0002_auto_20191107_1647")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="img_link",
            field=models.CharField(
                default="/images/cover_image_plaseholder.jpg",
                max_length=255,
                verbose_name="Cover image",
            ),
        )
    ]
