# Generated by Django 2.2.7 on 2019-11-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eng", "0003_auto_20191108_1035")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(
                help_text="Use Markdown syntax", verbose_name="Content"
            ),
        )
    ]
