# Generated by Django 2.2.7 on 2019-11-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eng", "0004_auto_20191108_1056")]

    operations = [
        migrations.CreateModel(
            name="EmailRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={"ordering": ["created_on"]},
        )
    ]
